Maiia full api
CovidTrackerFr/vitemadose pull request #207
Opened 2021-04-17 18:17 UTC by gaelbenoit

Le scrape HTML/API est remplacé par du full API

2021-04-17 18:19 UTC, gaelbenoit commented
ah j'ai oublié de mettre à jour les tests unitaires...

2021-04-17 18:27 UTC, gaelbenoit commented
voilà j'ai modifié les tests pour qu'ils soient joués sur des réponses d'API et pas du HTML

2021-04-17 19:59 UTC, Bouska requested changes

2021-04-17 19:59 UTC, Bouska commented on scraper/maiia/maiia.py
> +def parse_slots(slots: list) -> datetime:
Si on peut renvoyer un objet `datetime` ou `None`, il faut écrire : 
```suggestion
def parse_slots(slots: list) -> Optional[datetime]:
```
(ne pas oublier `from typing import Optional`)

2021-04-17 19:59 UTC, Bouska commented on scraper/maiia/maiia.py
> +def get_next_slot_date(center_id: str, consultation_reason_name: str, start_date: str, client: httpx.Client = DEFAULT_CLIENT) -> str:
```suggestion
def get_next_slot_date(center_id: str, consultation_reason_name: str, start_date: str, client: httpx.Client = DEFAULT_CLIENT) -> Optional[str]:
```

2021-04-17 19:59 UTC, Bouska commented on scraper/maiia/maiia.py
> +        return
```suggestion
        return None
```

2021-04-17 19:59 UTC, Bouska commented on scraper/maiia/maiia.py
> +    return
```suggestion
    return None
```

2021-04-17 19:59 UTC, Bouska commented on scraper/maiia/maiia.py
> +            return
```suggestion
            return None
```

2021-04-17 19:59 UTC, Bouska commented on scraper/maiia/maiia.py
> +    return
```suggestion
    return None
```

2021-04-17 19:59 UTC, Bouska commented on scraper/maiia/maiia.py
> +        availabilities = get_paged(url, limit=100000, client=client)['items']
Il y a t-il une raison pour utiliser une limite différente de `MAIIA_LIMIT` ?

2021-04-17 19:59 UTC, Bouska commented on scraper/maiia/maiia.py
> +    return result['items']
C'est joueur de se reposer sur l'API pour avoir la garantie que `result['items']` existe si `result['total']` existe.

2021-04-17 19:59 UTC, Bouska commented on scraper/maiia/maiia.py
> +def get_slots(center_id: str, consultation_reason_name: str, start_date: str, end_date: str, limit=MAIIA_LIMIT, client: httpx.Client = DEFAULT_CLIENT) -> list:
```suggestion
def get_slots(center_id: str, consultation_reason_name: str, start_date: str, end_date: str, limit=MAIIA_LIMIT, client: httpx.Client = DEFAULT_CLIENT) -> Optional[list]:
```

2021-04-17 19:59 UTC, Bouska commented on scraper/maiia/maiia.py
> +def get_first_availability(center_id: str, request_date: str, reasons: dict, client: httpx.Client = DEFAULT_CLIENT) -> [datetime, int]:
A fortiori, `reasons` vient de `get_reasons()` qui renvoie une `list de `dict`.
```suggestion
def get_first_availability(center_id: str, request_date: str, reasons: list[dict], client: httpx.Client = DEFAULT_CLIENT) -> [datetime, int]:
```

2021-04-17 19:59 UTC, Bouska commented on scraper/maiia/maiia.py
> +def get_first_availability(center_id: str, request_date: str, reasons: dict, client: httpx.Client = DEFAULT_CLIENT) -> [datetime, int]:
Apparemment on peut retourner `None, 0`, donc même : 
```suggestion
def get_first_availability(center_id: str, request_date: str, reasons: list[dict], client: httpx.Client = DEFAULT_CLIENT) -> [Optional[datetime], int]:
```

2021-04-17 19:59 UTC, Bouska commented on scraper/maiia/maiia.py
> +        return
```suggestion
        return None
```

2021-04-17 19:59 UTC, Bouska commented on scraper/maiia/maiia.py
> +    reasons = reasons = get_reasons(center_id, client=client)
Huh?
```suggestion
    reasons = get_reasons(center_id, client=client)
```

2021-04-17 19:59 UTC, Bouska commented on scraper/maiia/maiia.py
> +    if '?centerid=' not in url:
Ne fait quelque chose d'aussi barbare, profite de `urllib.parse` :
```suggestion
    url_query = parse_qs(urlparse.urlparse(url).query)
    if 'centerid' not in url_query:
```

2021-04-17 19:59 UTC, Bouska commented on scraper/maiia/maiia.py
> +    center_id = url.split('?centerid=')[1]
```suggestion
    center_id = url_query['centerid']
```

2021-04-17 19:59 UTC, Bouska commented on scraper/maiia/maiia.py
> +        return
```suggestion
        return None
```

2021-04-17 19:59 UTC, Bouska commented on scraper/maiia/maiia.py
> +        return
```suggestion
        return None
```

2021-04-17 19:59 UTC, Bouska commented on tests/test_maiia.py
> +        with open(path, encoding='utf8') as f:
Je ne sais pas si `utf8` est reconnu, normalement c'est `utf-8`

2021-04-17 20:30 UTC, gaelbenoit commented on scraper/maiia/maiia.py
> +    return result['items']
ma fonction get_page créé elle-même total et items pour remplir items de façon paginée, donc items existe forcément, mais je vais quand même tester

2021-04-17 20:36 UTC, gaelbenoit commented on scraper/maiia/maiia.py
> +        availabilities = get_paged(url, limit=100000, client=client)['items']
non en effet, je dois utiliser le limit passé à la fonction comme au premier appel

2021-04-17 20:36 UTC, gaelbenoit commented on scraper/maiia/maiia.py
> +    reasons = reasons = get_reasons(center_id, client=client)
oups

2021-04-17 20:37 UTC, gaelbenoit commented on tests/test_maiia.py
> +        with open(path, encoding='utf8') as f:
ça passe mais je vais quand même modifier

2021-04-17 21:02 UTC, Bouska commented on scraper/maiia/maiia.py
> +    if '?centerid=' not in url:
My bad, il faut rajouter les imports `from urlib.parse import urlpase, parse_qs` et écrire `url_query = parse_qs(urlparse(url).query)`

2021-04-18 11:11 UTC, Noezor commented
LGTM, bonne review Bouska !

2021-04-18 12:07 UTC, Noezor commented
C'est OK pour merge ça ? On a un problème avec Maiia, et je pense que je vais éviter de lancer dans un fix si cette PR le résout #212

2021-04-18 12:16 UTC, Bouska approved these changes
Looks good to me :+1: Il faudra juste penser à faire des rebases les prochaines fois, parce que c'est un massacre niveau commits :sweat_smile:

2021-04-18 12:36 UTC, gaelbenoit commented
> C'est OK pour merge ça ? On a un problème avec Maiia, et je pense que je vais éviter de lancer dans un fix si cette PR le résout #212

je te confirme qu'avec ma version je n'ai pas de rdv pour la pharmacie de l'Aquarius

`75119 Pharmacie de l'Aquarius: no appointment found`

2021-04-18 12:44 UTC, Noezor commented
Let's gooooooooooooo

2021-04-18 13:10 UTC, aureliancnx approved these changes

2021-04-18 13:10 UTC, merged