Ajout metadata "last_edit_date" pour stats.json
CovidTrackerFr/vitemadose pull request #242
Opened 2021-04-24 07:50 UTC by Noezor

Pour #240

2021-04-25 07:50 UTC, tlevillayer commented on stats_generation/stats_available_centers.py
> +from datetime import date, datetime
date n'est pas utilisé au final ?

2021-04-25 11:35 UTC, Bouska requested changes

2021-04-25 11:35 UTC, Bouska commented on stats_generation/stats_available_centers.py
> +        "last_edit_date":datetime.now().strftime("%Y-%m-%d %H:%M:%S")
On utilise généralement `isoformat()` pour les autres dates dans nos JSON, donc je recommanderai d'utiliser le même. (Et un petit espace après les `:` ce serait pas mal)

2021-04-25 11:35 UTC, Bouska commented on stats_generation/stats_available_centers.py
> +def plus_metadata(stats : dict) -> dict:
Pas d'espace avant un `:` (pep8 toussa toussa)

2021-04-25 16:24 UTC, Bouska requested changes

2021-04-25 16:24 UTC, Bouska commented on stats_generation/stats_available_centers.py
> -    with open(f"data/output/{stats_path}", "w") as stats_file:
Tu as changé l'API d'`export_centres_stats()` (pourquoi pas), par conséquent tu as cassé le test de [`test_stat_count()`](https://github.com/CovidTrackerFr/vitemadose/blob/b011b144ad36d292a9b109ea7207f09d7c9e1d3d/tests/test_stats.py#L8). Soit tu maintiens ton changement d'API tu changes le test, soit tu conserves l'API actuelle et le test passera.

2021-04-25 16:24 UTC, Bouska commented on stats_generation/stats_available_centers.py
> +
Rajoute une ligne vide en plus ([PEP8](https://www.python.org/dev/peps/pep-0008/#blank-lines) encore une fois)

2021-04-25 17:13 UTC, Noezor commented on stats_generation/stats_available_centers.py
> -    with open(f"data/output/{stats_path}", "w") as stats_file:
C'était totalement une erreur ! Je corrige ça :)

2021-04-25 19:18 UTC, Noezor commented on stats_generation/stats_available_centers.py
> -    with open(f"data/output/{stats_path}", "w") as stats_file:
En fait c'est pas moi qui ai bougé le code, c'est le code qui a bougé autour de moi et le merge qui s'est pas bien résolvé

2021-04-25 19:25 UTC, Bouska commented on stats_generation/stats_available_centers.py
> -    with open(f"data/output/{stats_path}", "w") as stats_file:
Oula /o\ En voulant ramener les changements de main, de un tu as fait sauter la moitié de tes changements, et de deux, tu ramènes une tonne de changement qui n'a rien à voir. Besoin d'un coup de main pour gérer les subtilités de git ?

2021-04-25 20:02 UTC, Noezor commented on stats_generation/stats_available_centers.py
> -    with open(f"data/output/{stats_path}", "w") as stats_file:
Et mince j'ai fait le bourrin à tout merge ... bon, je reprendrai du commit d'avant demain et ferai qqch de propre...

2021-04-27 20:31 UTC, Noezor commented
@Bouska bon j'ai fix les tests ... mais ça a pas clean les changements... oops

2021-05-01 08:50 UTC, Noezor commented
Bon ... je suis chaud pour refaire une PR. Le cherry pick et hard reset a pas marché ...

2021-05-01 21:20 UTC, remichaignon commented
@Noezor J'ai cherry-pick tes commits dans une nouvelle PR: https://github.com/CovidTrackerFr/vitemadose/pull/298

2021-05-02 14:34 UTC, closed without merging