mapharma corrections fallback opendata & tests
CovidTrackerFr/vitemadose pull request #254
Opened 2021-04-26 18:53 UTC by gaelbenoit

j'ai corrigé le fallback opendata de mapharma. L'idée de ce fallback est d'utiliser la dernière version sauvegardée si l'API opendata ne répond pas. Le fallback allait chercher un fichier dans data/output mais en fait doit aller le chercher sur la branche data-auto
J'en ai profité pour ajouter des shims supplémentaires pour les tests unitaires qui étaient un peu faussés (enfin un peu sur le live en fait)

2021-04-26 21:49 UTC, aureliancnx approved these changes

2021-04-26 21:54 UTC, Bouska requested changes

2021-04-26 21:54 UTC, Bouska commented on scraper/mapharma/mapharma.py
> +        request = client.get(MAPHARMA_OPEN_DATA_URL_FALLBACK, headers=MAPHARMA_HEADERS)
Ici, tu veux utiliser `opendata_url_fallback`, avec l'argument par défaut, tu auras le même comportement.

2021-04-26 21:54 UTC, Bouska commented on scraper/mapharma/mapharma.py
> +        logger.warning(f'{base_url} returned error {hex.response.status_code}')
```suggestion
        logger.warning(f'{opendata_url_fallback} returned error {hex.response.status_code}')
```

2021-04-26 21:54 UTC, Bouska commented on scraper/mapharma/mapharma.py
>      except httpx.HTTPStatusError as hex:
Comme j'avais le nez dans le code de Keldoc, est ce qu'on ne gérerait pas aussi les timeout ici ? :thinking:

2021-04-26 21:54 UTC, Bouska commented on scraper/mapharma/mapharma.py
> +def get_mapharma_opendata(client: httpx.Client = DEFAULT_CLIENT, opendata_url: str = MAPHARMA_OPEN_DATA_URL, opendata_url_fallback: str = MAPHARMA_OPEN_DATA_URL_FALLBACK) -> dict:
Ligne trop longue (PEP8 toussa toussa) (pas la seule, cf. l.41, l.100 & l.142)

2021-04-26 21:54 UTC, Bouska commented on scraper/mapharma/mapharma.py
>          logger.warning(f'{base_url} returned error {hex.response.status_code}')
```suggestion
        logger.warning(f'{opendata_url} returned error {hex.response.status_code}')
```

2021-04-26 21:54 UTC, Bouska commented on tests/test_mapharma.py
> +        print(request.url)
C'est volontaire de garder ce `print` ici ?

2021-04-26 21:58 UTC, gaelbenoit commented on tests/test_mapharma.py
> +        print(request.url)
non c'est un oubli, je crois que je vais attendre demain matin pour faire les corrections 😴😴😴

2021-04-27 08:42 UTC, Bouska commented on scraper/mapharma/mapharma.py
> +    except TimeoutException as hex:
```suggestion
    except httpx.TimeoutException as hex:
```

2021-04-27 08:45 UTC, Bouska commented on scraper/mapharma/mapharma.py
>      opendate = list
Je pense qu'il y a une typo (et je ne suis pas sûr que l'initialisation par `list` fonctionne). Ça devrait plutôt être ça je pense.
```suggestion
    opendata = list() 
```

2021-04-27 18:40 UTC, Bouska approved these changes
C'est bon pour moi 👍

2021-04-27 18:41 UTC, merged