ARNm lorsque AZ et (+55 ans suite)
CovidTrackerFr/vitemadose pull request #260
Opened 2021-04-27 22:33 UTC by Noezor

Fixes #230 

J'ai aussi fait 2-3 petits refacto.

Draft car je dois ajouter des tests

2021-04-27 22:34 UTC, Noezor commented on scraper/pattern/center_info.py
> +            self.vaccine_type = [(vaccine.value if isinstance(vaccine, Vaccine) else vaccine) for vaccine in self.vaccine_type]
Vraiment pas fière de cette ligne, mais je n'ai pas su trouver où on passait des `str` après mon update

2021-04-29 19:51 UTC, Bouska requested changes

2021-04-29 19:51 UTC, Bouska commented on scraper/pattern/center_info.py
> +    if "-" in name and "55" in name and "suite" in name:
Tu es bien trop restrictif ici. Voici une série de remarques : 
- ne fait pas de test sur `suite`, potentiellement que ce mot ne sera pas là (tu pourrais avoir "après", "post", etc.)
- `55` pourrait être écrit en toutes lettres et avec des typos
- `-` pourrait être écrit en toutes lettres aussi ou par d'autres caractères typographiques `−` (voir `–` ou `-`)

2021-04-29 19:51 UTC, Bouska commented on scraper/pattern/center_info.py
> +def get_vaccine_name(name : str, fallback: Vaccine = None) -> Vaccine :
```suggestion
def get_vaccine_name(name: str, fallback: Vaccine = None) -> Vaccine:
```

2021-04-29 19:56 UTC, Bouska commented on scraper/pattern/center_info.py
> +            self.vaccine_type = [(vaccine.value if isinstance(vaccine, Vaccine) else vaccine) for vaccine in self.vaccine_type]
Je pense que la logique n'est pas bonne. Je pense que la bonne idée serait d'avoir un vaccin `indéterminé` et de le mettre comme vaccin par défaut (et comme fallback aussi).

2021-04-30 11:21 UTC, Maijin commented on scraper/pattern/center_info.py
> +            self.vaccine_type = [(vaccine.value if isinstance(vaccine, Vaccine) else vaccine) for vaccine in self.vaccine_type]
Il y a deja une fonction - get_vaccine_name

2021-04-30 13:47 UTC, Noezor commented on scraper/pattern/center_info.py
> +    if "-" in name and "55" in name and "suite" in name:
Je suis d'accord, mais c'est impossible d'être exhaustif sur ces règles de toute façon. Je les rajouterai au fûr et à mesure que des bugs sont remontés (pour le momen, ça passe les 2 cas remontés)

2021-04-30 13:47 UTC, Noezor commented on scraper/pattern/center_info.py
> +            self.vaccine_type = [(vaccine.value if isinstance(vaccine, Vaccine) else vaccine) for vaccine in self.vaccine_type]
En fait, c'est juste pour déserialiser les Vaccine (de l'Enum). Sauf que des fois, c'est bien des strings (comme avant) qui sont passées, etj 'ai pas réussi à traquer d'o↓ ca venait

2021-04-30 14:09 UTC, merged

2021-04-30 15:26 UTC, Maijin commented
Du coup est-ce que tu peux reouvrir cette PR @Noezor