module to parse ordoclic
CovidTrackerFr/vitemadose pull request #33
Opened 2021-04-04 13:21 UTC by gaelbenoit

2021-04-04 13:25 UTC, aureliancnx requested changes

2021-04-04 13:25 UTC, aureliancnx commented on scraper/ordoclic.py
> +    r = session.post(base_url, data=json.dumps(payload), headers=headers)
r.raise_for_status() permet de débugger les cas où il y a un problème avec la requête

2021-04-04 13:25 UTC, aureliancnx commented on scraper/ordoclic.py
> +    r = session.get(base_url)
pareil, r.raise_for_status()

2021-04-04 13:25 UTC, aureliancnx commented on scraper/ordoclic.py
> +    r = session.get(base_url, params=payload)
pareil, r.raise_for_status()

2021-04-04 13:25 UTC, aureliancnx commented on scraper/ordoclic.py
> +    r = session.get(base_url)
pareil, r.raise_for_status()

2021-04-04 13:26 UTC, aureliancnx commented
ça a l'air pas mal, tu as testé ? Pour les requêtes, je t'invite à ajouter ce que j'ai mis dans la review, on fait ça pour avoir une meilleure trace lors du scrapping pour s'assurer qu'il n'y a pas de problème particulier.

Sinon leur API a l'air bien plus simple à utiliser pour récupérer la data! :)

2021-04-04 13:40 UTC, aureliancnx commented
Merci 👍

2021-04-04 13:44 UTC, aureliancnx approved these changes

2021-04-04 13:45 UTC, Maijin commented on scraper/ordoclic.py
> +    payload = {'page': '1', 'per_page': '500', 'in.isCovidVaccineSupported': 'true', 'in.isPublicProfile': 'true' }
J'aurai mis direct les 10k si c'est bien la limite haute, ou meme mieux deja implementer le crawl de toute les pages avec un for / if pour etre sur qu'au moment ou y aura plus de lieu on ne les loupe pas 😃

2021-04-04 13:46 UTC, Maijin commented on scraper/ordoclic.py
> +    base_url = 'https://api.ordoclic.fr/v1/solar/entities/{0}/reasons'.format(entityId)
Les autres modules utilisent les f-strings en python3 pourrait etre pas mal d'unifier cela 👍 

https://github.com/CovidTrackerFr/vitemadose/blob/main/scraper/prototype.py#L33

2021-04-04 15:40 UTC, gaelbenoit commented
bon j'ai ajouté une fonction de test qui va chercher toutes les pharma juste avec le champ in.isPublicProfile comme filtre, mais à partir de là je suis un peu perdu, comment on intègre cette liste dans le scraper?

2021-04-04 20:30 UTC, Floby commented on scraper/ordoclic.py
> +def fetch_slots(rdv_site_web, start_date):
je n'arrive pas trop à comprendre ce qui est censé arriver dans `rdv_site_web` c'est le lien ordoclic ? d'où vient-il ?

2021-04-04 20:46 UTC, gaelbenoit commented on scraper/ordoclic.py
> +def fetch_slots(rdv_site_web, start_date):
oui c'est le lien de prise de rdv, je le récupère sur l'api de recherche (https://api.ordoclic.fr/v1/public/search)

2021-04-04 21:12 UTC, Maijin commented on scraper/ordoclic.py
> +            yield centre
Je pense on pourrait mettre un 
else
print(“Ordoclic: Entite f'{item.get("type")) non supporté')
vu qu'on a pas logging

2021-04-04 21:49 UTC, Bouska commented on scraper/ordoclic.py
> +            first_availability = datetime.strptime(nextAvailableSlotDate, '%Y-%m-%dT%H:%M:%S%z') + timedelta(minutes=120)
Avec `timedelta(minutes=120)`, on hardcode un décalage sur l'heure d'été de France métropolitaine, je ne recommande pas. A défaut de `timeStartUtcOffset` ou équivalent dans les données, je propose de gérer a minima l'heure métropolitaine d'hiver et d'été :
```suggestion
            first_availability = datetime.strptime(nextAvailableSlotDate, '%Y-%m-%dT%H:%M:%S%z')
            first_availability += first_availability.replace(tzinfo=timezone('CET')).utcoffset()
```
En oubliant pas `from pytz import timezone`

2021-04-04 21:49 UTC, Bouska commented on scraper/ordoclic.py
> +        if date is None:
`date` ne peut pas être égal à None, si `strptime()` plante il va lever une exception, donc cette vérification n'est pas utile.

2021-04-04 21:49 UTC, Bouska commented on scraper/ordoclic.py
> +                    first_availability = date
nit: tabulation en trop

2021-04-04 21:49 UTC, Bouska commented on scraper/ordoclic.py
> +            payload["departement"] = item["location"]["zip"][:2]
Dans la majorité des cas, ce raccourci va fonctionner. Mais dans un certains nombre de cas, ça ne va pas être le cas (DOM [3 chiffres], Corse [2A/2B, code postal en 20xxx], et [les autres cas](https://fr.wikipedia.org/wiki/Liste_des_communes_de_France_dont_le_code_postal_ne_correspond_pas_au_d%C3%A9partement)). Je ne sais pas comment les autres sources gèrent ça.

2021-04-04 21:49 UTC, Bouska commented on scraper/ordoclic.py
> +        start_date = datetime.now().isoformat()[:10]
Ca fonctionne mais utiliser `strftime('%Y-%m-%d')` ce serait quand même plus propre.
```suggestion
        start_date = datetime.now().strftime("%Y-%m-%d")
```

2021-04-04 22:52 UTC, Bouska commented on scraper/ordoclic.py
> +            centre["com_insee"] = item["location"]["zip"]
Le code postal est différent du code INSEE. Ordoclic ne fourni pas le code INSEE de la commune, il faudrait donc avoir un système de conversion de code postale vers code INSEE à partir de cette base de données : https://www.data.gouv.fr/fr/datasets/correspondance-code-insee-code-postal/

2021-04-05 01:54 UTC, grubounet commented
Bonjour tout le monde, je suis nouveau et je voudrais aider comme je peux ^^
J'ai du mal à comprendre comment vous passez du numéro de département récupéré sur VMD aux codes postaux, vu que la majorité des API possèdent le CP

Vous testez tous les CP du département en une seule requête get ? 

J'ai essayé avec le 01 par exemple et la requête était trop longue donc rejetée, j'imagine qu'il doit y avoir une manière plus intelligente de faire ?

2021-04-05 06:14 UTC, gaelbenoit commented on scraper/ordoclic.py
> +            payload["departement"] = item["location"]["zip"][:2]
moi non plus mais j'ai trouvé une table de correspondance sur https://www.data.gouv.fr/fr/datasets/correspondance-code-insee-code-postal/. Je fais un premier jet pour mapper cp/insee mais ça mérite d'être réfléchi

2021-04-05 06:49 UTC, gaelbenoit commented on scraper/ordoclic.py
> +            yield centre
le problème c'est que je n'ai pas toujours le champ type, par exemple pour un médecin je ne l'aurai pas, mais à la place des champs job & title... je vais sonder un peu le code de leur site web pour voir comment ils discriminent les enregistrements

2021-04-05 12:22 UTC, Bouska commented on scraper/ordoclic.py
> +def cp_to_insee(cp):
Pour l'instant, le reste des scrapers passent par la base de données du ministère pour récupérer les RDV disponibles des centres listés. Base de données qui contient le code INSEE et code postal de chaque centre. Apparemment, il y a des centres qui manquent de cette liste. Tout ça pour dire que c'est probable que cette fonction risque d'être utile à d'autre module donc je te propose de la mettre dans un module à part.

2021-04-05 12:22 UTC, Bouska commented on scraper/ordoclic.py
> +        url = "https://www.data.gouv.fr/fr/datasets/r/e88c6fda-1d09-42a0-a069-606d3259114e"
Premièrement, j'ai fait une erreur, ce dataset est exclusivement pour l'Ile de France (en même temps je trouvais ça louche que la Region Ile de France fasse une base de donnée pour la France entière). Prends plutôt ce dataset de la Poste https://www.data.gouv.fr/fr/datasets/base-officielle-des-codes-postaux/ ; d'autant plus qu'il a beaucoup moins de données inutiles pour nous.

Deuxièmement, il est assez peu probable que le dataset change de si tôt. C'est préférable qu'on en stocke une copie local, plutôt que faire un appel d'API a chaque fois qu'on lance le script.

2021-04-05 12:22 UTC, Bouska commented on scraper/ordoclic.py
> +    for record in insee:
Si on conserve une copie locale, ça pourrait être intéressant de la conserver triée par code postal afin de pouvoir faire une recherche par dichtomie plutôt qu'une recherche linéaire.

2021-04-05 12:22 UTC, Bouska commented on scraper/ordoclic.py
> +                print(f"Ordoclic: Type {t} non pris en charge")
Je ne comprends pas trop l'intérêt de récupérer des données puis de ne pas les utiliser, autant s'éviter le boulot et ne pas les récupérer :thinking:

2021-04-05 12:32 UTC, Maijin commented on scraper/ordoclic.py
> +                print(f"Ordoclic: Type {t} non pris en charge")
Le soucis c'etait qu'on etait pas sur pourquoi Ordoclic avait des non-pharmacients avec des prise de rendez-vous. Maintenant on sait et je pense on peut surement ajouter en commentaire cette portion au vu du call

2021-04-05 14:15 UTC, aureliancnx commented
Je réfléchis un peu par rapport à l’implémentation d’Ordoclic. Actuellement, on a uniquement des centres de vaccination et on arrive à quatre/cinq centres avec des disponibilités dans certains départements.

Est-ce qu’il y a eu des tests avec Ordoclic pour savoir à peu près combien de centres disponibles ça nous ajoute à l’instant T, pour savoir si au niveau du front on affichera un nombre raisonnable de propositions de rendez-vous et pas une trentaine de pharmacies par département par exemple. Parce que si c’est le cas, on devra réfléchir à l’implémentation d’un filtre : pharmacies, centres de vaccination.. ? Pour éviter de noyer l’utilisateur avec 50 cards

2021-04-05 14:20 UTC, gaelbenoit commented
> Je réfléchis un peu par rapport à l’implémentation d’Ordoclic. Actuellement, on a uniquement des centres de vaccination et on arrive à quatre/cinq centres avec des disponibilités dans certains départements.
> 
> Est-ce qu’il y a eu des tests avec Ordoclic pour savoir à peu près combien de centres disponibles ça nous ajoute à l’instant T, pour savoir si au niveau du front on affichera un nombre raisonnable de propositions de rendez-vous et pas une trentaine de pharmacies par département par exemple. Parce que si c’est le cas, on devra réfléchir à l’implémentation d’un filtre : pharmacies, centres de vaccination.. ? Pour éviter de noyer l’utilisateur avec 50 cards

pour l'instant on remonte 157 pharmacies dont 14 avec des dispos

2021-04-05 14:25 UTC, aureliancnx commented
OK donc ça reste raisonnable on a pas besoin de s’occuper des filtres pour l’instant je pense

2021-04-05 15:30 UTC, Maijin approved these changes

2021-04-05 19:07 UTC, Bouska approved these changes

2021-04-05 19:07 UTC, Bouska commented on test_ordoclic.py
> +    date = ordoclic_fetch_slots(website, datetime.now().strftime('%Y-%m-%d'))
Je vais chippoter un peu, mais ce serait plus simple de d'appeler une seule fois `datetime.now().strftime('%Y-%m-%d')` et de le stocker dans une variable que de le regénérer à chaque appel de fonction.

2021-04-05 19:07 UTC, Bouska commented on scraper/ordoclic.py
> +    return str(first_availability)
On s'attend à une date au format ISO en retour, il faut donc faire :
```suggestion
    return first_availability.isoformat()
```

2021-04-05 19:47 UTC, merged