[DOCTOLIB] Select correct address for a center
CovidTrackerFr/vitemadose pull request #414
Opened 2021-05-11 22:14 UTC by tlevillayer

**Checklist**

- [ ] Fix #issue
- [ ] J'ai ajouté des tests (si nécessaire)
- [x] J'ai formatté/identé mon code en utilisant [black](https://github.com/psf/black) - `black -l 120 fileXX fileYY`

**Description**

Change the order between two dict to select the address from the place if possible

2021-05-11 23:15 UTC, tlevillayer commented on scraper/doctolib/doctolib_center_scrap.py
> +        infos_page["gid"] = "d{0}".format(place["id"])
Sans cette modification, plusieurs centre d'un meme etablissement ont le meme gid. Est-ce un problème ? La solution proposée ici est celle de mettre l'idée de place. Par contre il contient aussi des lettres

2021-05-12 20:58 UTC, Noezor commented on scraper/doctolib/doctolib_center_scrap.py
> +        infos_page["gid"] = "d{0}".format(place["id"])
C'est un problème connu depuis longtemps. On a jugé que c'était pas important car le GID ne nous sert à rien en pratique.

2021-05-12 20:58 UTC, Noezor commented
LGTM

2021-05-12 21:00 UTC, tlevillayer commented on scraper/doctolib/doctolib_center_scrap.py
> +        infos_page["gid"] = "d{0}".format(place["id"])
Si, le gid est utilisé pour les notifications justement :/

2021-05-12 21:35 UTC, Noezor requested changes

2021-05-12 21:35 UTC, Noezor commented on scraper/doctolib/doctolib_center_scrap.py
> +        infos_page["gid"] = "d{0}".format(place["id"])
Ah, bachibouzouk ... Tu peux virer juste ce changement de la PR et en faire une autre pour ça, en expliquant l'interet ? (Je crois que du coup les notifs vont shoot peu importe le centre qui a des nouvelles dispos)

2021-05-12 23:53 UTC, closed without merging