Various cleanups
CovidTrackerFr/vitemadose pull request #466
Opened 2021-05-14 14:38 UTC by ValentinMouret

**Checklist**

- [x] J'ai formatté/identé mon code en utilisant [black](https://github.com/psf/black) - `black -l 120 fileXX fileYY`

**Description**

En lisant le code, j’ai vu plusieurs aspects que je pouvais simplifier/réorganiser.
La plupart des changements sont triviaux (formatting, unused imports).

2021-05-14 17:39 UTC, Bouska requested changes
Refactoring bienvenu ! (ça va me bousillé ma PR sur mypy mais je ne suis plus à ça près x]à

2021-05-14 17:39 UTC, Bouska commented on scraper/pattern/center_location.py
> +        if long and lat:
Même si concrètement ça va revenir au même, c'est mieux d'avoir un `return None` explicite dans une fonction/méthode dont on attend un retour.

2021-05-14 17:39 UTC, Bouska commented on scraper/pattern/center_location.py
> +            if "address" in data and not city and not cp:
Avec ton changement, si `city` ou `cp `est nulle mais pas les deux, on va écraser la valeur récupérée de la plateforme par une valeur parsée, et j'aurais tendance à plus faire confiance à la valeur de la plateforme qu'à la valeur parsée.

2021-05-14 17:39 UTC, Bouska commented on scraper/export/export_pool.py
> -import sys
Par curiosité, tu utilises quel outil pour détecter les import non utilisés ?

2021-05-14 18:15 UTC, ValentinMouret commented on scraper/export/export_pool.py
> -import sys
Haha, VSCode qui me met le truc en sombre :D

2021-05-15 01:58 UTC, aureliancnx commented on scraper/export/export_pool.py
> -import sys
Pycharm a également la même chose & on peut utiliser Optimize Imports

2021-05-15 11:42 UTC, ValentinMouret commented on scraper/doctolib/doctolib.py
> +def parse_agenda_ids(rdata: dict) -> List[int]:
Done.

2021-05-15 11:42 UTC, ValentinMouret commented on scraper/doctolib/doctolib.py
> +    def pop_practice_id(self, request: ScraperRequest) -> None:
Done.

2021-05-15 13:41 UTC, merged