Prise en compte du rang d'injection pour AvecMonDoc
CovidTrackerFr/vitemadose pull request #679
Opened 2022-01-15 13:23 UTC by gaelbenoit

**Checklist**

- [x] Fix #678 

**Description**

Le rang d'injection n'est pas détecté par le scraper AvecMonDoc. Du coup le front-end qui filtre part rang d'injection connu n'affiche plus les créneaux disponibles car ils ne sont pas associés à un rang d'injection. J'ai donc ajouté la détection du rang en fonction du motif (Première injection, Deuxième injection, Troisième injection), tout en ajoutant les deuxièmes et troisièmes injection comme motifs valides dans le fichier config.json

2022-01-15 21:53 UTC, Bouska requested changes
Dans l'état, ça ne va pas fonctionner parce que les raisons retournées par AvecMonDoc actuellement ne collent plus à ce qu'on a dans `valid_reasons`

2022-01-15 21:53 UTC, Bouska commented on scraper/avecmondoc/avecmondoc.py
> +        self, availabilities: list, request: ScraperRequest, vaccine: Vaccine, dose: list = None
Pour être pointilleux, si `dose` peut être égal à `None`, c'est de type `Optional[list]`

2022-01-15 21:53 UTC, Bouska commented on scraper/avecmondoc/avecmondoc.py
> +def get_vaccine_dose(motive_name):
Si on veut faire les choses bien :
```suggestion
def get_vaccine_dose(motive_name: str) -> Optional[list]:
```

2022-01-15 21:53 UTC, Bouska commented on config.json
> +                    "Troisième injection vaccinale COVID",
Est ce que tu as déduis ces raisons à partir des autres raisons valides ? Parce que quand je vais sur une pharmacie qui a des créneaux (https://patient.avecmondoc.com/fiche/structure/pharmacie-de-coeuilly-703), les motifs ne collent avec aucun des "raisons valides" actuellement utilisées (https://api.avecmondoc.com/api/Organizations/getConsultationReasons?params={"organizationId":703})

2022-01-15 22:18 UTC, Bouska commented on config.json
> +                    "Troisième injection vaccinale COVID",
My bad, je viens de voir que c'est bon pour les médecins, mais pas les pharmacies. Tu peux merger ce patch pour les médecins et j'en ferais un autre pour les pharmacies, ou sinon tu peux tout faire d'un coup.

2022-01-15 22:34 UTC, Bouska commented on config.json
> +                    "Troisième injection vaccinale COVID",
Il semblerait qu'en pharmacie, les motifs sont libres... Voici une autre pharmacie avec encore d'autres motifs : https://api.avecmondoc.com/api/Organizations/getConsultationReasons?params=%7B%22organizationId%22%3A632%2C%22doctorId%22%3A709%7D

2022-01-16 04:07 UTC, gaelbenoit commented on config.json
> +                    "Troisième injection vaccinale COVID",
En fait j'ai surtout regardé le centre signalé par l'équipe avecmondoc (CIAMT ITALIE ET VITEMADOSE). Ah oui tes exemples sont intéressants, le premier vaut la peine d'être ajouté, le second j'hésite 😅 c'est vraiment très raccourci

2022-01-16 12:36 UTC, Bouska commented on config.json
> +                    "Troisième injection vaccinale COVID",
Ça vaudrait peut-être la peine de rajouter un test `Xè` qui rajoute une dose `1, 2, 3` ; mais ce n'est pas très grave si ce n'est pas présent.

2022-01-16 12:38 UTC, Bouska approved these changes
Ça me semble bon :+1:

2022-01-17 09:09 UTC, merged