Ajout du scraping de doctolib pour les centres de rdv
CovidTrackerFr/vitemadose pull request #86
Opened 2021-04-07 00:42 UTC by grubounet

Creation de la fonction doctolib_getcsv_scrap(is_professionnel) 

Cette fonction est à appeler 1 ou 2 fois par jour, elle génère un fichier csv (un pour les pros ou un pour les non pros selon le paramètre passé) contenant les centres scrapés

Adaptation de la fonction centre_iterator()
Conservation du code original dans un 1er temps, puis comparaison des centres dans le fichier csv des centres scrapés avec les centres du fichier data.gouv
Les centres supplémentaires (dans le csv scrapé mais pas dans le fichier data.gouv) sont analysés par la suite si ils existent

2021-04-07 00:46 UTC, grubounet commented
Il faudra penser à adapter le WebDriver que j'ai configuré pour mon path windows

2021-04-07 11:43 UTC, aureliancnx requested changes

2021-04-07 11:43 UTC, aureliancnx commented on scraper/departements.py
> +
ligne en trop

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +                    if len(url_tronquée_gouv.split("?"))!=0:
trop de blocs d'indentation, essaye de séparer en plusieurs fonctions
norme PEP `if len(url_tronquée_gouv.split("?")) != 0:`

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +                options.binary_location = r'C:\Program Files\Mozilla Firefox\firefox.exe'
idem ici pour le nombre de blocs

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +        main()
indentation en trop

2021-04-07 11:43 UTC, aureliancnx commented on scripts/install
> -PYTHON="python3"
non ?

2021-04-07 11:43 UTC, aureliancnx commented on scripts/scrape
> -${BIN}python scrape.py
remet pour le scraper

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +                while remain_pages == True:
Il est d'usage de mettre `remain_pages` tout court, c'est la même chose que de faire `remain_pages == True`

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +
séparations de lignes inutiles

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +                        remain_pages=False
norme PEP `remain_pages = False`

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +                    executable_path=r'C:\Users\AppData\Local\Programs\Python\Python38-32\geckodriver.exe', firefox_options=options)
le scrapper ne tourne pas sur windows, il faut changer le path

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +        # On créée le fichier et on met les en tête des colonnes. Encodage utf8 pour les accents
indentation en trop?

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +                if len(row_scrapée['rdv_site_web'].split("/"))==6:
norme PEP `len(row_scrapée['rdv_site_web'].split("/")) == 6`

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +                    url_tronquée=row_scrapée['rdv_site_web'].split("/")[4]+"/"+row_scrapée['rdv_site_web'].split("/")[5]
norme PEP `url_tronquée = row_scrapée['rdv_site_web'].split("/")[4] + "/" + row_scrapée['rdv_site_web'].split("/")[5]`

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +                    if len(url_tronquée.split("?"))!=0:
norme PEP `len(url_tronquée.split("?")) != 0:`

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +                        url_tronquée=url_tronquée.split("?")[0]
norme PEP `url_tronquée = url_tronquée.split("?")[0]`

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +                    artificial_dict={'gid': row_scrapée["gid"], 'nom':row_scrapée["nom"], 'com_insee':row_scrapée["com_insee"], 'rdv_site_web':row_scrapée["rdv_site_web"]}
norme PEP, espacer le nom de la variable du = et l'assignation

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +                if centres_gouvernement_parsed.count(url_tronquée)==0:
norme PEP, espacer les comparateurs par un espace à gauche et à droite du =

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +                        centres_scrapés_doctolib[url_tronquée]=row_scrapée['rdv_site_web']
norme PEP, espacer le nom de la variable du = et l'assignation

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +                        url_tronquée_gouv=url_tronquée_gouv.split("?")[0]
norme PEP, espacer le nom de la variable du = et l'assignation

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +                    url_tronquée_gouv=row_scrapée_gouv['rdv_site_web'].split("/")[4]+"/"+row_scrapée_gouv['rdv_site_web'].split("/")[5]
norme PEP, espacer le nom de la variable du = et l'assignation

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +        with open(url_csv_centres_scrapés_doctolib, newline='',encoding="utf-8") as url_csv_centres_scrapés_doctolib:
espace manquant entre la virgule `newline='', encoding="utf-8"`

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +    # on fait un try/catch pour ne pas tout planter si le fichier csv scrapé n'existe pas
Dans le cas où il y a un plantage, il vaut mieux laisser le scraper s'occuper de try/catch et d'afficher le message d'erreur en fonction de l'exception avec le logger

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +    centres_scrapés_doctolib={}
pareil norme PEP =

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +    centres_gouvernement_parsed=[]
pareil norme PEP =

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +    read_csv_gouv= csv.DictReader(read_csv_gouv, delimiter=';')
pareil norme PEP =

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +                if len(row_scrapée_gouv['rdv_site_web'].split("/"))==6:
norme PEP, espacer les comparateurs par un espace à gauche et à droite du =

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +    departements={"01":"ain","02":"aisne","03":"allier","04":"alpes-de-haute-provence","05":"hautes-alpes","09":"alpes-maritimes","07":"ardeche","08":"ardennes","09":"ariege","10":"aube","11":"aude",
norme PEP, espace nécessaire à gauche et à droite du =

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +                        remain_pages=alse
typo `remain_pages = False`

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +                if len(numero_departement)==2:
norme PEP, espacer les comparateurs par un espace à gauche et à droite du =

2021-04-07 11:43 UTC, aureliancnx commented on scraper/scraper.py
> +                elif len(numero_departement)==3:
norme PEP, espacer les comparateurs par un espace à gauche et à droite du =

2021-04-07 11:44 UTC, aureliancnx commented
Quelques petites problèmes de coding style et d'indentation qui réduisent la clarté de la lisibilité du code, avec trop de blocs d'indentation parfois (tu peux faire plusieurs fonctions qui exécutent quelque chose en particulier puis faire un appel)

Changer le path du gecko aussi

2021-04-08 08:07 UTC, Maijin commented
![](https://github.trello.services/images/mini-trello-icon.png) [d](https://trello.com/c/TiLxQjer/1-d)

2021-04-08 08:08 UTC, Maijin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajout du scraping de doctolib pour les centres de rdv](https://trello.com/c/TiLxQjer/1-ajout-du-scraping-de-doctolib-pour-les-centres-de-rdv)

2021-04-09 21:58 UTC, closed without merging