Ajout cp_to_insee dans departements.py
CovidTrackerFr/vitemadose pull request #95
Opened 2021-04-07 15:09 UTC by tlevillayer

2021-04-07 15:25 UTC, Maijin commented
Peut etre regarder vmd_logger pour la partie logging :)

2021-04-07 15:53 UTC, tlevillayer commented
> Peut etre regarder vmd_logger pour la partie logging :)

C'est à dire ?

2021-04-07 15:55 UTC, Maijin commented
Je t'ai envoyé les details sur telegram mais c'est bon en fait ;)

2021-04-07 20:34 UTC, Jordan11 commented
En fait c'est la PR 79 les gars avec un fichier JSON qui contient tous les bons codes il faudrait la merge @Maijin

2021-04-08 16:36 UTC, tlevillayer commented
@Jordan11 , j'ai pris en compte les changements effectués sur le main

2021-04-10 08:47 UTC, Maijin approved these changes

2021-04-10 08:49 UTC, Maijin commented
Est-ce que tu peux refactor ordoclic pour utiliser cette fonction du coup?

2021-04-10 09:11 UTC, Maijin requested changes
Manque le return

2021-04-10 09:28 UTC, merged